[package]
name = "aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
post = { path = "../post" }
clap = { version = "4.5.17", features = ["derive"] }
regex = "1.10.6"
chrono = "0.4.38"
lazy_static = "1.5.0"
